---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deploy
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: spc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: spc-pod
      labels:
        app: spc
    spec:
      containers:
        - name: spc
          image: yaswithaa/spc:DEV
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080

---
apiVersion: v1 
kind: Service
metadata:
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - name: webport
      port: 35000
      targetPort: 8080
